settings = {}
settings["REQUIRED_ENV_VARS"] = ["TOPIC_OUT","TOPIC_CONTROL","KAFKA_CONFIG"]

settings["TICKER_DATA_NOT_AVAILABLE"]='N/A'


ENV_VAR_TOPIC_CONTROL = 'TOPIC_CONTROL'
ENV_VAR_TOPIC_OUT = 'TOPIC_OUT'
ENV_VAR_KAFKA_CONFIG = 'KAFKA_CONFIG'
TICKER_DATA_NOT_AVAILABLE = 'N/A'



