apiVersion: v1
kind: Pod
metadata:
  name: cassandra-client
  labels:
    app: cassandra
spec:
  containers:
    - image: docker.io/kakicode/cassandra-client
      name: cassandra-client
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP 

  