swagger: "2.0"
info:
  version: "0.0.1"
  title: controller app
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths
basePath: /api
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /fin/ticker/{ticker}:
    x-swagger-router-controller: fin
    get:
      description: Returns what if finds in google finance
      operationId: getTicker
      parameters:
        - name: ticker
          in: path
          description: The ticker in format EX:STOCK
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
#    post:
#      description: persists message
#      operationId: post
#      parameters:
#        - name: msg
#          description: msg to be persisted
#          in: body
#          required: true
#          schema:
#            $ref: "#/definitions/Msg"
#      responses:
#        "200":
#          description: Success
#          schema:
#            $ref: "#/definitions/GeneralResponse"
#        default:
#          description: Error
#          schema:
#            $ref: "#/definitions/ErrorResponse"

  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  SuccessResponse:
    type: object
    properties:
      ok:
        type: boolean
        description: text message to be echoed
      result:
        type: schema
        description: result wrapping the outcome
    required:
      - ok
      - result